//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18047
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SudokuCalcs.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SudokuCalcs.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 1.在处理数据上，Peter将所有的格子下了定义，每个格子叫square，每行叫row，
        ///  每列叫column，一个square所关联的Row，column，和那个九宫格都叫做Unit，
        ///  而这些row，column和Unit的总和叫做Peers。
        ///2.对于空的格子，每个格子都会有123456789出现的情况，而已经选定的格子，则
        ///  值是唯一的。开始计算时，先选定有数字的格子，然后在这个格子所在的Peers
        ///  中删除这个数字。比如在第一行的第一个是1，第二个的可能性是123456789，
        ///  那么在第二个的可能性里面删除1，变成23456789。
        ///3.遍历每个值未定的square，找到格子中可选值最少的返回，如果是可选数为1，
        ///  则该格子唯一被确定，并删除Peers中其他格子中的该值得选项，
        ///4.如果获取的格子可选数大于1，则选择其中的一个值，作为确定值，并把其他值
        ///  连同坐标，以及当前整个软件中的每个格子的情况进行记录，然后推送到栈结
        ///  构中，然后继续执行，
        ///5.如果返回格子的可选值为空，这是因为刚才选择的值有问题，所以需要进行一次
        ///  出栈操作，提取剩余值，并将软件 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string GameArithmetic {
            get {
                return ResourceManager.GetString("GameArithmetic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在9x9的格子中，用1到9九个阿拉伯数字填充整个格子，要求符合：
        ///1.每一行都用到1-9，位置不限；
        ///2.每一列都用到1-9，位置不限；
        ///3.每3x3的格子(软件中用不同颜色区分)都用到1-9，位置不限。 的本地化字符串。
        /// </summary>
        internal static string GameRule {
            get {
                return ResourceManager.GetString("GameRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap moyun {
            get {
                object obj = ResourceManager.GetObject("moyun", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Sudoku {
            get {
                object obj = ResourceManager.GetObject("Sudoku", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
